### ISSUE TITLE
API throttle when using GCS as checkpoint backend

### ISSUE THREAD

**Issue by gbto** [ArroyoSystems/arroyo#621] opened 2024-05-07 08:08 UTC
We have observed on our Kubernetes deployments some responsiveness issue in the UI. After investigation, we've discovered the API calls made to fetch pipelines and jobs were pending and eventually timed out. Digging deeper, this was due to the controller calling the GCP metadata server too often:

`object_store::gcp::credential::fetching token from metadata server`

Which results in:

`object_store::client::retry::Encountered transport error (error sending request for url (http://metadata/computeMetadata/v1/instance/service-accounts/default/token?audience=https%3A%2F%2Fwww.googleapis.com%2Foauth2%2Fv4%2Ftoken): error trying to connect: operation timed out) backing off for 0.1 seconds, retry 1 of 10`

So after an attempt to reduce the number of `object_store::gcp::credential` call to the metadata server, I've switched from [Kubernetes SA authentication](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity?cloudshell=false#kubernetes-sa-to-iam) to passing the serialised JSON of the SA credentials as `GOOGLE_SERVICE_ACCOUNT_KEY` environment variable, which did reduce the number of calls but did not resolve the unresponsive Arroyo API issue. I also tried hacking the object_store by forcing it to use the S3 client for authenticating to GCS with `AWS_DEFAULT_REGION`, `AWS_ENDPOINT` but had no luck for the authentication...

Here are the screenshots of what that looks like in practice:

<img width="1799" alt="Screenshot_2024-05-06_at_18 33 00" src="https://github.com/ArroyoSystems/arroyo/assets/29350919/153385f5-2c4b-4d1b-a249-36127f6f14bc">
<img width="1547" alt="Screenshot 2024-05-06 at 18 34 45" src="https://github.com/ArroyoSystems/arroyo/assets/29350919/f32d1176-6c8f-4ee1-af0b-9ec9bd094066">

Happy to help if there's anything I can do !

**Comment by mwylde** [comment] 2024-10-24 21:20
We believe we have found the root cause of this issue within the object_store crate, and have opened https://github.com/apache/arrow-rs/issues/6625 there.

**Comment by mwylde** [comment] 2024-10-29 00:35
Fixed in #770

**Closed by mwylde** 2024-10-29 00:35 UTC
Labels: bug
